# Generated by Django 3.1.5 on 2021-02-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='played_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='active_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
