# Generated by Django 3.1.5 on 2021-02-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20210206_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='ScoreTransaction',
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
