# Generated by Django 3.1.5 on 2021-02-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20210206_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
    ]
